name: Run tests

on:
    push:
    pull_request:

jobs:
    php-tests:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                php: [ 7.2.5 ]
                laravel: [ 7.* ]
                dependency-version: [ prefer-lowest, prefer-stable ]
                os: [ ubuntu-latest, windows-latest ]

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v1

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version:  ${{ matrix.php }}
                  tools: dom, curl, libxml, mbstring, zip, pcntl, pdo, bcmath, soap, intl, exif
                  coverage: none

            - name: Install dependencies
              run: |
                  composer require --no-interaction --no-update
                  composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

            - name: Execute tests
              run: vendor/bin/phpunit
