name: Run tests

on:
    push:
    pull_request:

jobs:
    php-tests:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                php: [ 8.0, 7.3 ]
                laravel: [ 8.* ]
                dependency-version: [ prefer-lowest, prefer-stable ]
                os: [ ubuntu-latest, windows-latest ]
                include:
                    -   laravel: 8.*
                        testbench: 6.*

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v1

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version:  ${{ matrix.php }}
                  tools: dom, curl, libxml, mbstring, zip, pcntl, pdo, bcmath, soap, intl, exif
                  coverage: none

            - name: Install dependencies
              run: |
                  composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                  composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

            - name: Execute tests
              run: vendor/bin/phpunit
